### ISSUE TITLE
Please add a plugin to timeout / kill jobs

### ISSUE THREAD

**Issue by fgrehm** [PetroFeed/dockerized-jenkins#4]
:pray:

**Comment by gtramontina** [comment]
https://github.com/PetroFeed/dockerized-jenkins/commit/ae969cb10e5080ef2d6a2f46cce0423d8d046678 added

**Comment by filipesperandio** [comment]
i saw it, not sure how to use it

**Comment by gtramontina** [comment]
You set it up at the job level.
